name: Publish SysWhispers3 docs via GitHub Pages
on:
  push:
    branches:
      - master
      - refactor

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: set lower case project name
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >>${GITHUB_ENV}
          echo "REPO_NAME_LC=${REPO_NAME,,}" >>${GITHUB_ENV}

      - name: Prepare docs using lazydocs
        run: |
          echo "[+] Install plugins"
          pip install lazydocs mkdocs-awesome-pages-plugin
          export PYTHONPATH=$PWD
          echo "[+] Generate documentation of ${REPO_NAME_LC}/ using \"https://github.com/${{ github.repository }}/blob/master\" as base-url..."
          lazydocs --output-path="./docs/documentation" --overview-file="README.md" --src-base-url="https://github.com/${{ github.repository }}/blob/master" ${REPO_NAME_LC}/

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: docs_requirements.txt
